/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lujain.gltf 
Author: Egor Liashchuk (https://sketchfab.com/egorliashchuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/guest-house-848c5cd323984d0db036e3dc1d734d5c
Title: Guest House
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/lujain.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" scale={0.1}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Empty_7" position={[7.934, 15.526, 0.074]} scale={2.915}>
                <group name="BezierCurve005_0" position={[-0.092, 0.272, -0.208]} scale={.343}>
                  <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Material} />
                </group>
                <group name="Cube033_1" position={[0.723, -0.331, -0.058]} scale={0.343}>
                  <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material} />
                </group>
                <group name="Cube047_2" position={[0.723, -0.331, -0.058]} scale={0.343}>
                  <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material} />
                </group>
                <group name="Cylinder004_3" position={[0.157, 0.19, -0.191]} scale={0.343}>
                  <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Material} />
                </group>
                <group name="Plane003_4" position={[-0.073, 0.021, -0.146]} scale={0.343}>
                  <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Material} />
                </group>
                <group name="Plane008_5" position={[-0.034, 0.138, -0.162]} scale={0.343}>
                  <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Material} />
                </group>
                <group name="signboard_6" position={[-0.073, 0.021, -0.211]} scale={0.343}>
                  <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Material} />
                </group>
              </group>
              <group name="Empty001_8" position={[-3.397, 14.895, 5.803]} scale={2.454} />
              <group name="Empty002_9" position={[2.799, 0.726, -1.013]} />
              <group name="Empty004_10" position={[5.845, 0.725, -1.013]} />
              <group name="Empty005_78" scale={18.723}>
                <group name="Armature_17" position={[-0.181, 1.133, 0.312]} rotation={[0, 0, Math.PI]} scale={[0.053, 0.049, 0.053]}>
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="Dragon001_62_correction" position={[-3.398, 23.293, -5.846]} rotation={[0, 0, -Math.PI]} scale={[18.723, 20.552, 18.723]}>
                      <group name="Dragon001_62" />
                    </group>
                    <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Material} skeleton={nodes.Object_33.skeleton} />
                  </group>
                </group>
                <group name="Armature001_22" position={[0.147, 0.264, -0.054]} rotation={[0, 0, Math.PI]} scale={0.053}>
                  <group name="GLTF_created_1">
                    <primitive object={nodes.GLTF_created_1_rootJoint} />
                    <group name="flag_66_correction" position={[2.753, 4.935, 1.02]} rotation={[0, 0, -Math.PI]} scale={18.723}>
                      <group name="flag_66" />
                    </group>
                    <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Material} skeleton={nodes.Object_43.skeleton} />
                  </group>
                </group>
                <group name="Armature002_27" position={[0.229, 0.264, -0.054]} rotation={[0, 0, Math.PI]} scale={0.053}>
                  <group name="GLTF_created_2">
                    <primitive object={nodes.GLTF_created_2_rootJoint} />
                    <group name="flag001_67_correction" position={[4.28, 4.935, 1.02]} rotation={[0, 0, -Math.PI]} scale={18.723}>
                      <group name="flag001_67" />
                    </group>
                    <skinnedMesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.Material} skeleton={nodes.Object_53.skeleton} />
                  </group>
                </group>
                <group name="Armature003_32" position={[0.31, 0.264, -0.054]} rotation={[0, 0, Math.PI]} scale={0.053}>
                  <group name="GLTF_created_3">
                    <primitive object={nodes.GLTF_created_3_rootJoint} />
                    <group name="flag002_68_correction" position={[5.807, 4.935, 1.02]} rotation={[0, 0, -Math.PI]} scale={18.723}>
                      <group name="flag002_68" />
                    </group>
                    <skinnedMesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.Material} skeleton={nodes.Object_63.skeleton} />
                  </group>
                </group>
                <group name="BezierCurve002_33" position={[0.076, 0.289, 0.066]} scale={0.053}>
                  <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.Material} />
                </group>
                <group name="Cube001_34" position={[-0.29, 0.516, 0.112]} scale={0.053}>
                  <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.Material} />
                </group>
                <group name="Cube002_35" position={[0.448, 0.408, 0]} rotation={[0, Math.PI / 2, 0]} scale={0.053}>
                  <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.Material} />
                </group>
                <group name="Cube003_36" position={[0.013, 0.471, -0.005]} scale={0.053}>
                  <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.Material} />
                </group>
                <group name="Cube004_37" position={[-0.106, 0.516, 0.112]} scale={0.053}>
                  <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.Material} />
                </group>
                <group name="Cube005_38" position={[-0.251, 0.882, 0.112]} scale={0.053}>
                  <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Material} />
                </group>
                <group name="Cube006_39" position={[-0.177, 0.591, 0.018]} scale={0.053}>
                  <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.Material} />
                </group>
                <group name="Cube007_40" position={[-0.323, 0.58, -0.011]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.053}>
                  <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.Material} />
                </group>
                <group name="Cube008_41" position={[0.241, 0.451, -0.113]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.053, 0.053, 0.053]}>
                  <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.Material} />
                </group>
                <group name="Cube009_42" position={[-0.172, 0.689, 0.121]} scale={0.053}>
                  <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Material} />
                </group>
                <group name="Cube010_43" position={[-0.184, 0.936, 0]} scale={0.053}>
                  <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.Material} />
                </group>
                <group name="Cube014_44" position={[0.047, 0.815, 0]} scale={0.053}>
                  <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.Material} />
                </group>
                <group name="Cube015_45" position={[0.437, 0.49, 0]} scale={0.053}>
                  <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.Material} />
                </group>
                <group name="Cube021_46" position={[0.392, 0.467, 0.001]} rotation={[0, Math.PI / 2, 0]} scale={0.053}>
                  <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.Material} />
                </group>
                <group name="Cube022_47" position={[-0.183, 0.829, 0.084]} scale={0.053}>
                  <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.Material} />
                </group>
                <group name="Cube024_48" position={[0.128, 0.55, 0.003]} scale={0.053}>
                  <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.Material} />
                </group>
                <group name="Cube026_49" position={[-0.531, 0.411, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.053}>
                  <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.Material} />
                </group>
                <group name="Cube027_50" position={[0.241, 0.451, 0.113]} scale={0.053}>
                  <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.Material} />
                </group>
                <group name="Cube028_51" position={[0.504, 0.449, -0.003]} scale={0.053}>
                  <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.Material} />
                </group>
                <group name="Cube029_52" position={[-0.618, 0.452, 0.02]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.053}>
                  <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.Material} />
                </group>
                <group name="Cube030_53" position={[-0.123, 0.559, 0.21]} scale={0.053}>
                  <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.Material} />
                </group>
                <group name="Cube032_54" position={[-0.177, 0.591, 0]} scale={0.053}>
                  <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.Material} />
                </group>
                <group name="Cube035_55" position={[0.139, 0.247, 0]} scale={0.053}>
                  <mesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.Material} />
                </group>
                <group name="Cube037_56" position={[-0.16, 0.974, 0.005]} scale={0.053}>
                  <mesh name="Object_111" geometry={nodes.Object_111.geometry} material={materials.Material} />
                </group>
                <group name="Cube038_57" position={[-0.26, 0.957, 0.104]} scale={0.053}>
                  <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.Material} />
                </group>
                <group name="Cube041_58" position={[0.396, 0.515, 0]} scale={0.053}>
                  <mesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.Material} />
                </group>
                <group name="Cube044_59" position={[-0.513, 0.469, 0.001]} rotation={[0, -Math.PI / 2, 0]} scale={0.053}>
                  <mesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.Material} />
                </group>
                <group name="Cube046_60" position={[0.107, 0.75, 0.001]} rotation={[0, Math.PI / 2, 0]} scale={0.053}>
                  <mesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.Material} />
                </group>
                <group name="Dragon_61" position={[-0.093, 1.059, 0.028]} rotation={[0, 0, 0.32]} scale={0.053}>
                  <mesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.Material} />
                </group>
                <group name="Engine_1_64" position={[-0.566, 0.287, 0.004]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.053}>
                  <mesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.Material} />
                </group>
                <group name="Engine_2_65" position={[-0.093, 0.242, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.053}>
                  <mesh name="Object_125" geometry={nodes.Object_125.geometry} material={materials.Material} />
                </group>
                <group name="Floor_1_69" position={[0.197, 0.279, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.053}>
                  <mesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.Material} />
                </group>
                <group name="Floor_2_70" position={[-0.557, 0.505, 0]} scale={0.053}>
                  <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.Material} />
                </group>
                <group name="Pipe_2_71" position={[-0.18, 1.148, 0.108]} scale={0.053}>
                  <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.Material} />
                </group>
                <group name="Pipe_3_72" position={[-0.052, 0.232, 0.155]} scale={0.053}>
                  <mesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.Material} />
                </group>
                <group name="Plane_73" position={[-0.184, 0.825, 0.108]} rotation={[Math.PI / 2, 0, 0]} scale={0.053}>
                  <mesh name="Object_135" geometry={nodes.Object_135.geometry} material={materials.Material} />
                </group>
                <group name="Plane001_74" position={[-0.092, 0.123, 0.379]} rotation={[0.611, 0, 0]} scale={0.053}>
                  <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.Material} />
                </group>
                <group name="Plane002_75" position={[0.546, 0.27, -0.006]} rotation={[Math.PI / 2, 0.96, -Math.PI / 2]} scale={0.053}>
                  <mesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.Material} />
                </group>
                <group name="Roof_76" position={[-0.177, 0.692, 0]} scale={0.053}>
                  <mesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.Material} />
                </group>
                <group name="Words_1_77" position={[0.205, 0.31, 0.075]} rotation={[1.965, 0, 0.006]} scale={0.053}>
                  <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.Material} />
                </group>
              </group>
              <group name="pIPE_NIZ_79" position={[3.716, 4.556, -0.371]}>
                <mesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.Material} />
              </group>
              <group name="Cube_80" position={[-5.54, 11.853, 2.473]}>
                <mesh name="Object_147" geometry={nodes.Object_147.geometry} material={materials.Material} />
              </group>
              <group name="Cube034_81" position={[1.828, 18.384, 3]} rotation={[-Math.PI, 1.57, -Math.PI]}>
                <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.Material} />
              </group>
              <group name="Words_2001_83" position={[4.657, 20.71, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <group name="Words_2_82" position={[-0.004, -0.019, 0.368]}>
                  <mesh name="Object_153" geometry={nodes.Object_153.geometry} material={materials.Material} />
                </group>
                <mesh name="Object_151" geometry={nodes.Object_151.geometry} material={materials.Material} />
              </group>
              <group name="pIPE_NIZ001_84" position={[3.716, 4.556, -0.371]}>
                <mesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.Material} />
              </group>
              <group name="pIPE_NIZ002_85" position={[3.716, 4.556, -0.371]}>
                <mesh name="Object_157" geometry={nodes.Object_157.geometry} material={materials.Material} />
              </group>
              <group name="pIPE_NIZ003_86" position={[1.256, 3.427, -0.113]}>
                <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.Material} />
              </group>
              <group name="Cube011_87" position={[-4.831, 11.853, 2.473]}>
                <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.Material} />
              </group>
              <group name="Cube012_88" position={[-4.121, 11.853, 2.473]}>
                <mesh name="Object_163" geometry={nodes.Object_163.geometry} material={materials.Material} />
              </group>
              <group name="Cube013_89" position={[-3.412, 11.853, 2.473]}>
                <mesh name="Object_165" geometry={nodes.Object_165.geometry} material={materials.Material} />
              </group>
              <group name="Cube016_90" position={[-2.703, 11.853, 2.473]}>
                <mesh name="Object_167" geometry={nodes.Object_167.geometry} material={materials.Material} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lujain.gltf')
