/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mash.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mash.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.mushroom_mat} position={[0, 0, 0]}  scale={0.3}/>
      </group>
      <spotLight intensity={400} angle={0.64} penumbra={0.813} decay={2} color="#ffb2de" position={[4.076, 5.904, -2.005]} rotation={[-0.79, 0.41, 1.383]} />
      <PerspectiveCamera makeDefault={false} far={100} near={0.1} fov={22.895} position={[7.359, 4.958, 6.926]} rotation={[-0.627, 0.71, 0.441]} />
    </group>
  )
}

useGLTF.preload('/mash.gltf')
